import {
  PaletteColor,
  PaletteColorOptions,
} from '@mui/material/styles/createPalette'

/* AUTOGENERATED. YOUR CHANGES MAY BE OVERWRITTEN */

declare module '@mui/material/styles/createPalette' {
  interface PaletteOptions {
    'primary-light'?: PaletteColorOptions
    'primary-main'?: PaletteColorOptions
    'primary-dark'?: PaletteColorOptions
    'secondary-light'?: PaletteColorOptions
    'secondary-main'?: PaletteColorOptions
    'secondary-dark'?: PaletteColorOptions
    'tertiary-light'?: PaletteColorOptions
    'tertiary-main'?: PaletteColorOptions
    'tertiary-dark'?: PaletteColorOptions
    'text-primary-light'?: PaletteColorOptions
    'text-primary-main'?: PaletteColorOptions
    'text-primary-dark'?: PaletteColorOptions
    'text-secondary-light'?: PaletteColorOptions
    'text-secondary-main'?: PaletteColorOptions
    'text-secondary-dark'?: PaletteColorOptions
    'text-primary-invert-light'?: PaletteColorOptions
    'text-primary-invert-main'?: PaletteColorOptions
    'text-primary-invert-dark'?: PaletteColorOptions
    'text-secondary-invert-light'?: PaletteColorOptions
    'text-secondary-invert-main'?: PaletteColorOptions
    'text-secondary-invert-dark'?: PaletteColorOptions
    'border-primary-light'?: PaletteColorOptions
    'border-primary-main'?: PaletteColorOptions
    'border-primary-dark'?: PaletteColorOptions
  }

  interface Palette {
    'primary-light': PaletteColor
    'primary-main': PaletteColor
    'primary-dark': PaletteColor
    'secondary-light': PaletteColor
    'secondary-main': PaletteColor
    'secondary-dark': PaletteColor
    'tertiary-light': PaletteColor
    'tertiary-main': PaletteColor
    'tertiary-dark': PaletteColor
    'text-primary-light': PaletteColor
    'text-primary-main': PaletteColor
    'text-primary-dark': PaletteColor
    'text-secondary-light': PaletteColor
    'text-secondary-main': PaletteColor
    'text-secondary-dark': PaletteColor
    'text-primary-invert-light': PaletteColor
    'text-primary-invert-main': PaletteColor
    'text-primary-invert-dark': PaletteColor
    'text-secondary-invert-light': PaletteColor
    'text-secondary-invert-main': PaletteColor
    'text-secondary-invert-dark': PaletteColor
    'border-primary-light': PaletteColor
    'border-primary-main': PaletteColor
    'border-primary-dark': PaletteColor
  }
}

declare module '@mui/material' {
  interface ButtonPropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }

  interface TextFieldPropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }

  interface InputBasePropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }

  interface FormLabelPropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }

  interface SvgIconPropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }

  interface IconButtonPropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }

  interface CheckboxPropsColorOverrides {
    'primary-light': true
    'primary-main': true
    'primary-dark': true
    'secondary-light': true
    'secondary-main': true
    'secondary-dark': true
    'tertiary-light': true
    'tertiary-main': true
    'tertiary-dark': true
    'text-primary-light': true
    'text-primary-main': true
    'text-primary-dark': true
    'text-secondary-light': true
    'text-secondary-main': true
    'text-secondary-dark': true
    'text-primary-invert-light': true
    'text-primary-invert-main': true
    'text-primary-invert-dark': true
    'text-secondary-invert-light': true
    'text-secondary-invert-main': true
    'text-secondary-invert-dark': true
    'border-primary-light': true
    'border-primary-main': true
    'border-primary-dark': true
  }
}
