import { createTheme } from '@mui/material'

/* AUTOGENERATED. YOUR CHANGES MAY BE OVERWRITTEN */

const paletteOptions = {
  'primary-light': {
    main: '#768fff',
    contrastText: '#ffffff',
  },
  'primary-main': {
    main: '#2962ff',
    contrastText: '#ffffff',
  },
  'primary-dark': {
    main: '#0039cb',
    contrastText: '#ffffff',
  },
  'secondary-light': {
    main: '#8e8e8e',
    contrastText: '#ffffff',
  },
  'secondary-main': {
    main: '#616161',
    contrastText: '#ffffff',
  },
  'secondary-dark': {
    main: '#373737',
    contrastText: '#ffffff',
  },
  'tertiary-light': {
    main: '#ffff6b',
    contrastText: '#ffffff',
  },
  'tertiary-main': {
    main: '#fdd835',
    contrastText: '#ffffff',
  },
  'tertiary-dark': {
    main: '#c6a700',
    contrastText: '#ffffff',
  },
  'text-primary-light': {
    main: '#484848',
    contrastText: '#ffffff',
  },
  'text-primary-main': {
    main: '#212121',
    contrastText: '#ffffff',
  },
  'text-primary-dark': {
    main: '#000000',
    contrastText: '#ffffff',
  },
  'text-secondary-light': {
    main: '#4f5b62',
    contrastText: '#ffffff',
  },
  'text-secondary-main': {
    main: '#263238',
    contrastText: '#ffffff',
  },
  'text-secondary-dark': {
    main: '#000a12',
    contrastText: '#ffffff',
  },
  'text-primary-invert-light': {
    main: '#ffffff',
    contrastText: '#ffffff',
  },
  'text-primary-invert-main': {
    main: '#ffffff',
    contrastText: '#ffffff',
  },
  'text-primary-invert-dark': {
    main: '#ffffff',
    contrastText: '#ffffff',
  },
  'text-secondary-invert-light': {
    main: '#ffffff',
    contrastText: '#ffffff',
  },
  'text-secondary-invert-main': {
    main: '#ffffff',
    contrastText: '#ffffff',
  },
  'text-secondary-invert-dark': {
    main: '#ffffff',
    contrastText: '#ffffff',
  },
  'border-primary-light': {
    main: '#cfcfcf',
    contrastText: '#ffffff',
  },
  'border-primary-main': {
    main: '#9e9e9e',
    contrastText: '#ffffff',
  },
  'border-primary-dark': {
    main: '#707070',
    contrastText: '#ffffff',
  },
}

const theme = createTheme({
  palette: paletteOptions,
})

export default theme
